(function(root){
'use strict';
var URL='ws://127.0.0.1:39091/gauge-sync/v1',KEY='msfslogger.gauge.pairing.v1',OLD='msfslogger.cdu.config.v1',BACKOFF=[0,250,500,1000,2000,4000,8000,15000,30000];
var ls={status:[],log:[],exit:[]},pending={},ws=null,phase='DOWN',welcome=null,state=null,seq=0,snapshot=0,attempt=0,retry=null,stable=null,stopped=false,handshakeId=null,pairCode=null,pairSent=false,fresh=false,freshTimer=null,keepalive=null,watchdog=null,connectTimer=null;
try{root.localStorage.removeItem(OLD);}catch(e){}
function copy(v){return v===undefined?undefined:JSON.parse(JSON.stringify(v));}
function own(o,k){return Object.prototype.hasOwnProperty.call(o,k);}
function idok(v,n){return typeof v==='string'&&new RegExp('^[A-Za-z0-9_-]{'+n+'}$').test(v);}
function bytes(v){return unescape(encodeURIComponent(v)).length;}
function integer(v,min,max){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=min&&v<=max;}
function object(v){return v&&Object.prototype.toString.call(v)==='[object Object]';}
function exact(v,keys){if(!object(v))return false;var a=Object.keys(v).sort(),b=keys.slice().sort();return a.length===b.length&&a.join('|')===b.join('|');}
function bounded(v,depth){var keys,i;if(depth>16)return false;if(typeof v==='string')return bytes(v)<=4096;if(v===null||typeof v==='boolean'||typeof v==='number')return typeof v!=='number'||isFinite(v);if(Object.prototype.toString.call(v)==='[object Array]'){if(v.length>128)return false;for(i=0;i<v.length;i++)if(!bounded(v[i],depth+1))return false;return true;}if(!object(v))return false;keys=Object.keys(v);if(keys.length>64)return false;for(i=0;i<keys.length;i++)if(bytes(keys[i])>4096||!bounded(v[keys[i]],depth+1))return false;return true;}
function nullable(v,test){return v===null||test(v);}
function text(v,max){return typeof v==='string'&&bytes(v)<=max;}
function config(v){return exact(v,['version','serverUrl','trafficEnabled','trafficRadiusM','sim','autoUplink','tokenSet'])&&v.version===1&&text(v.serverUrl,2048)&&typeof v.trafficEnabled==='boolean'&&integer(v.trafficRadiusM,1000,200000)&&(v.sim==='2020'||v.sim==='2024')&&typeof v.autoUplink==='boolean'&&typeof v.tokenSet==='boolean';}
function configWrap(v){return exact(v,['exists','config'])&&typeof v.exists==='boolean'&&nullable(v.config,config);}
function problems(v){var fields={serverUrl:1,trafficEnabled:1,trafficRadiusM:1,sim:1,autoUplink:1,ingestToken:1,general:1},i,p;if(Object.prototype.toString.call(v)!=='[object Array]'||v.length>32)return false;for(i=0;i<v.length;i++){p=v[i];if(!exact(p,['field','code','message'])||!fields[p.field]||!text(p.code,2048)||!text(p.message,2048))return false;}return true;}
function status(v){var top=['v','type','at','app','sim','backend','pause','traffic','config'];return exact(v,top)&&v.v===1&&v.type==='status'&&integer(v.at,0,9007199254740991)&&exact(v.app,['state','running','problems','restarting','restartsRemaining'])&&text(v.app.state,2048)&&typeof v.app.running==='boolean'&&problems(v.app.problems)&&typeof v.app.restarting==='boolean'&&integer(v.app.restartsRemaining,0,5)&&exact(v.sim,['state','attempt','nextRetryAt','retryDelayMs','protocol','appName','appVersion','lastError'])&&text(v.sim.state,2048)&&integer(v.sim.attempt,0,9007199254740991)&&nullable(v.sim.nextRetryAt,function(x){return integer(x,0,9007199254740991);})&&nullable(v.sim.retryDelayMs,function(x){return integer(x,0,9007199254740991);})&&text(v.sim.protocol,2048)&&text(v.sim.appName,2048)&&nullable(v.sim.appVersion,function(x){return text(x,2048);})&&nullable(v.sim.lastError,function(x){return text(x,2048);})&&exact(v.backend,['state','httpStatus','lastOkAt','lastErrorAt','message'])&&text(v.backend.state,2048)&&nullable(v.backend.httpStatus,function(x){return integer(x,100,599);})&&nullable(v.backend.lastOkAt,function(x){return integer(x,0,9007199254740991);})&&nullable(v.backend.lastErrorAt,function(x){return integer(x,0,9007199254740991);})&&nullable(v.backend.message,function(x){return text(x,2048);})&&exact(v.pause,['state','flags','label','usingPauseEx1'])&&text(v.pause.state,2048)&&integer(v.pause.flags,0,9007199254740991)&&text(v.pause.label,2048)&&typeof v.pause.usingPauseEx1==='boolean'&&exact(v.traffic,['enabled','radiusM','lastSweepAt','lastBatchSize','lastError'])&&typeof v.traffic.enabled==='boolean'&&integer(v.traffic.radiusM,0,9007199254740991)&&nullable(v.traffic.lastSweepAt,function(x){return integer(x,0,9007199254740991);})&&nullable(v.traffic.lastBatchSize,function(x){return integer(x,0,9007199254740991);})&&nullable(v.traffic.lastError,function(x){return text(x,2048);})&&nullable(v.config,config);}
function full(b){return exact(b,['serviceInstanceId','connectionId','snapshotSeq','eventSeq','generatedAt','config','status'])&&idok(b.serviceInstanceId,22)&&idok(b.connectionId,22)&&integer(b.snapshotSeq,1,9007199254740991)&&integer(b.eventSeq,1,9007199254740991)&&integer(b.generatedAt,0,9007199254740991)&&configWrap(b.config)&&nullable(b.status,status);}
var ERROR_CODES={invalid_request:1,unsupported_version:1,unknown_type:1,unauthorized:1,forbidden:1,rate_limited:1,conflict:1,busy:1,timeout:1,internal:1};
function bodyOK(m,p){var b=m.body;if(m.type==='auth.result')return exact(b,['authorized'])&&b.authorized===true;if(m.type==='pair.result')return (exact(b,['paired'])&&b.paired===false)||(exact(b,['paired','capability','capabilityId'])&&b.paired===true&&idok(b.capability,43)&&idok(b.capabilityId,22));if(m.type==='session.welcome')return exact(b,['serviceInstanceId','connectionId','serverTime','capabilityId'])&&idok(b.serviceInstanceId,22)&&idok(b.connectionId,22)&&integer(b.serverTime,0,9007199254740991)&&idok(b.capabilityId,22);if(m.type==='state.full')return full(b);if(m.type==='status.event')return exact(b,['serviceInstanceId','connectionId','snapshotSeq','eventSeq','generatedAt','status'])&&idok(b.serviceInstanceId,22)&&idok(b.connectionId,22)&&integer(b.snapshotSeq,1,9007199254740991)&&integer(b.eventSeq,1,9007199254740991)&&integer(b.generatedAt,0,9007199254740991)&&status(b.status);if(m.type==='log.event')return exact(b,['serviceInstanceId','connectionId','eventSeq','at','level','message'])&&idok(b.serviceInstanceId,22)&&idok(b.connectionId,22)&&integer(b.eventSeq,1,9007199254740991)&&integer(b.at,0,9007199254740991)&&(b.level==='info'||b.level==='warn'||b.level==='error')&&text(b.message,2048);if(m.type==='exit.event')return exact(b,['serviceInstanceId','connectionId','eventSeq','at','code','signal','restarting','restartsRemaining'])&&idok(b.serviceInstanceId,22)&&idok(b.connectionId,22)&&integer(b.eventSeq,1,9007199254740991)&&integer(b.at,0,9007199254740991)&&nullable(b.code,function(x){return integer(x,-2147483648,2147483647);})&&nullable(b.signal,function(x){return text(x,32)&&/^[\x20-\x7E]*$/.test(x);})&&typeof b.restarting==='boolean'&&integer(b.restartsRemaining,0,5);if(m.type==='config.result')return exact(b,['ok','config'])&&b.ok===true&&configWrap(b.config);if(m.type==='config.path.result')return exact(b,['display'])&&b.display==='Managed by MSFSLogger desktop';if(m.type==='command.result')return exact(b,['ok','command','acceptedAt'])&&b.ok===true&&(b.command==='uplink.start'||b.command==='uplink.stop'||b.command==='sidecar.restart')&&integer(b.acceptedAt,0,9007199254740991);if(m.type==='error')return exact(b,['code','message','retryable'])&&ERROR_CODES[b.code]===1&&text(b.message,256)&&typeof b.retryable==='boolean';return false;}
function id(){var a=new Uint8Array(16),s='',i;if(!root.crypto||!root.crypto.getRandomValues)throw Error('Secure randomness unavailable');root.crypto.getRandomValues(a);for(i=0;i<a.length;i++)s+=('0'+a[i].toString(16)).slice(-2);return s;}
function capability(){try{var v=JSON.parse(root.localStorage.getItem(KEY)||'null');return v&&Object.keys(v).length===2&&v.v===1&&idok(v.capability,43)?v.capability:null;}catch(e){return null;}}
function emit(k,v){ls[k].slice().forEach(function(fn){try{fn(copy(v));}catch(e){}});}
function sub(k,fn){if(typeof fn!=='function')return function(){};ls[k].push(fn);return function(){var i=ls[k].indexOf(fn);if(i>=0)ls[k].splice(i,1);};}
function send(p){if(!ws||ws.readyState!==1||phase!=='READY')return false;if(p.action&&p.sent&&p.serviceInstanceId!==welcome.serviceInstanceId){fail(p,'Gauge action outcome uncertain');return false;}ws.send(p.text);p.sent=true;if(p.action&&!p.serviceInstanceId)p.serviceInstanceId=welcome.serviceInstanceId;return true;}
function fail(p,msg){if(!pending[p.id])return;delete pending[p.id];if(p.timer)root.clearTimeout(p.timer);if(p.expiry)root.clearTimeout(p.expiry);p.reject(Error(msg));}
function request(type,body,action){if(action&&phase!=='READY')return Promise.reject(Error('Gauge link unavailable'));var rid;try{rid=id();}catch(e){return Promise.reject(e);}return new Promise(function(resolve,reject){var p={id:rid,type:type,text:JSON.stringify({v:1,type:type,requestId:rid,body:body}),resolve:resolve,reject:reject,action:action,timer:null,expiry:null,serviceInstanceId:null};pending[rid]=p;if(action)p.expiry=root.setTimeout(function(){fail(p,'Gauge action outcome uncertain');},600000);if(!send(p)&&!action){p.timer=root.setTimeout(function(){fail(p,'Gauge link unavailable');},10000);connect();}});}
// Link state goes to the CDU message line so a simulator screenshot shows it.
function note(text,level){emit('log',{v:1,type:'log',at:0,level:level||'info',message:'GAUGE LINK '+text});}
function bad(code,label){note('PROTOCOL ERROR ('+String(label||'invalid message').slice(0,60)+')','error');if(ws)ws.close(code||1008,'Protocol error');}
function clearLinkTimers(){if(keepalive){root.clearTimeout(keepalive);keepalive=null;}if(watchdog){root.clearTimeout(watchdog);watchdog=null;}if(connectTimer){root.clearTimeout(connectTimer);connectTimer=null;}}
// Coherent GT may not answer WebSocket pings or report a server-side close, so
// the gauge proves the link itself: a small request inside the server's 30s
// idle limit, and a forced reconnect when it goes unanswered.
function keepAlive(){keepalive=root.setTimeout(function(){keepalive=null;if(phase!=='READY'||!ws)return;var done=function(){if(watchdog){root.clearTimeout(watchdog);watchdog=null;}};request('config.path.get',{},false).then(done,done);watchdog=root.setTimeout(function(){watchdog=null;if(phase==='READY')drop('no response');},9000);keepAlive();},25000);}
function drop(reason){var s=ws;note('LOST ('+reason+')','warn');if(!s)return;s.onopen=s.onmessage=s.onclose=s.onerror=null;try{s.close(4000,'Link watchdog');}catch(e){}closed();}
function common(m){var response=m&&m.requestId!==undefined;return exact(m,response?['v','type','requestId','body']:['v','type','body'])&&m.v===1&&typeof m.type==='string'&&object(m.body)&&(!response||idok(m.requestId,'16,64'))&&bounded(m,1)&&bodyOK(m);}
function same(b){return welcome&&b.serviceInstanceId===welcome.serviceInstanceId&&b.connectionId===welcome.connectionId;}
function settle(m){var p=pending[m.requestId],want;if(!p)return;if(m.type==='error')return fail(p,'Gauge request failed');want=p.type==='config.get'||p.type==='config.patch'?'config.result':p.type==='config.path.get'?'config.path.result':p.type==='state.get'?'state.full':'command.result';if(m.type!==want||(m.type==='command.result'&&m.body.command!==p.type))return bad(1008,'response '+m.type+' for '+p.type);if(p.type==='state.get'&&!same(m.body))return bad(1008,'state for another connection');delete pending[p.id];if(p.timer)root.clearTimeout(p.timer);if(p.expiry)root.clearTimeout(p.expiry);if(p.type==='config.get')p.resolve({exists:m.body.config.exists,config:copy(m.body.config.config),raw:copy(m.body.config.config)});else if(p.type==='config.patch')p.resolve({ok:true,path:'Managed by MSFSLogger desktop',config:copy(m.body.config.config)});else if(p.type==='config.path.get')p.resolve(m.body.display);else if(p.type==='state.get'){if(m.body.snapshotSeq>snapshot){state=copy(m.body);snapshot=m.body.snapshotSeq;seq=Math.max(seq,m.body.eventSeq);}p.resolve(copy(state.status));}else p.resolve(copy(m.body));}
function message(ev){if(typeof ev.data!=='string')return bad(1003,'binary frame');if(unescape(encodeURIComponent(ev.data)).length>32768)return bad(1009,'oversize message');var m;try{m=JSON.parse(ev.data);}catch(e){return bad(1007,'malformed json');}if(!common(m))return bad(1008,'invalid '+(m&&typeof m.type==='string'?m.type.slice(0,40):'message'));if(phase==='AUTH'){
 if(m.requestId!==handshakeId)return bad(1008,'unexpected '+m.type+' during auth');if(m.type==='error'){if(m.body.code==='unauthorized')try{root.localStorage.removeItem(KEY);}catch(e){}if(pairSent){pairSent=false;pairStatus('Code rejected or expired. Get a new code on the desktop app.');}return bad(1008,'authorization '+m.body.code);}
 if(m.type==='auth.result'&&m.body.authorized===true){phase='SYNC';return;}
 if(m.type==='pair.result'&&m.body.paired===false){pairSent=false;pairStatus('Code rejected. Get a new code on the desktop app.');return;}if(m.type==='pair.result'&&m.body.paired===true){pairSent=false;root.localStorage.setItem(KEY,JSON.stringify({v:1,capability:m.body.capability}));removeModal();note('PAIRED');phase='SYNC';return;}return bad(1008,'unexpected '+m.type+' during auth');}
 if(phase==='SYNC'){if(m.type==='session.welcome'){welcome=copy(m.body);return;}if(m.type!=='state.full'||!same(m.body))return bad(1008,'unexpected '+m.type+' during sync');state=copy(m.body);snapshot=m.body.snapshotSeq;seq=m.body.eventSeq;phase='READY';if(connectTimer){root.clearTimeout(connectTimer);connectTimer=null;}note('SYNCED ('+(state.status&&state.status.app?state.status.app.state:'no status')+')');if(state.status!==null)emit('status',state.status);keepAlive();Object.keys(pending).forEach(function(k){send(pending[k]);});stable=root.setTimeout(function(){if(phase==='READY')attempt=0;},10000);return;}
 if(phase!=='READY')return bad(1008,'unexpected '+m.type+' before sync');if(m.requestId!==undefined)return settle(m);if(!same(m.body))return bad(1008,m.type+' for another connection');if(m.type!=='status.event'&&m.type!=='log.event'&&m.type!=='exit.event')return bad(1008,'unexpected '+m.type);
 /* The server coalesces queued frames, so event numbers may skip; only a repeated or stale event is ignored. */
 if(m.body.eventSeq<=seq)return;seq=m.body.eventSeq;if(m.type==='status.event'){if(m.body.snapshotSeq<=snapshot)return;snapshot=m.body.snapshotSeq;state.status=copy(m.body.status);emit('status',state.status);}else if(m.type==='log.event')emit('log',{v:1,type:'log',at:m.body.at,level:m.body.level,message:m.body.message});else emit('exit',copy(m.body));}
function jitter(d){if(!d)return 0;var a=new Uint32Array(1),r=.5;if(root.crypto&&root.crypto.getRandomValues){root.crypto.getRandomValues(a);r=a[0]/4294967295;}return Math.round(d*(.8+r*.4));}
function closed(ev){var was=phase;ws=null;phase='DOWN';clearLinkTimers();if(ev&&(was==='READY'||was==='SYNC'))note('LOST ('+(ev.code||'closed')+(ev.reason?' '+String(ev.reason).slice(0,40):'')+')','warn');welcome=null;state=null;seq=0;snapshot=0;fresh=false;if(freshTimer){root.clearTimeout(freshTimer);freshTimer=null;}if(pairSent){pairSent=false;pairStatus('Link lost. Press Pair to try again.');}if(stable)root.clearTimeout(stable);if(!stopped&&!retry){var d=BACKOFF[Math.min(attempt,BACKOFF.length-1)];attempt++;retry=root.setTimeout(function(){retry=null;connect();},jitter(d));}}
function connect(){if(stopped||ws||typeof root.WebSocket!=='function')return;phase='CONNECTING';try{ws=new root.WebSocket(URL);}catch(e){ws=null;return closed();}connectTimer=root.setTimeout(function(){connectTimer=null;if(ws&&phase!=='READY')drop('timeout '+phase.toLowerCase());},12000);ws.onopen=function(){phase='AUTH';fresh=true;freshTimer=root.setTimeout(function(){fresh=false;freshTimer=null;},3000);var c=capability();if(c){handshakeId=id();ws.send(JSON.stringify({v:1,type:'auth.request',requestId:handshakeId,body:{capability:c}}));}else if(pairCode)sendPair();else modal();};ws.onmessage=message;ws.onclose=closed;ws.onerror=function(){};}
function removeModal(){var n=root.document&&root.document.getElementById('msfslogger-pairing');if(n&&n.parentNode)n.parentNode.removeChild(n);}
function pairStatus(t){var n=root.document&&root.document.getElementById('msfslogger-pairing'),s=n&&n.getElementsByTagName('div')[0];if(s)s.textContent=t;}
// The server allows 5s for the first message, so a code typed on a long-open
// socket would arrive too late. Hold the code and send it as the first message
// of a fresh connection instead.
function sendPair(){var code=pairCode;pairCode=null;pairSent=true;handshakeId=id();pairStatus('Pairing...');ws.send(JSON.stringify({v:1,type:'pair.request',requestId:handshakeId,body:{code:code,clientLabel:'MSFS CDU'}}));}
function submitPair(e){if(e&&e.preventDefault)e.preventDefault();var n=root.document&&root.document.getElementById('msfslogger-pairing');if(!n||pairSent)return false;var code=String(n.getElementsByTagName('input')[0].value||'').replace(/\s+/g,'');if(!/^[0-9]{8}$/.test(code)){pairStatus('Enter the 8-digit code from the desktop app.');return false;}pairCode=code;if(ws&&ws.readyState===1&&phase==='AUTH'&&fresh){sendPair();return false;}pairStatus('Connecting...');attempt=0;if(retry){root.clearTimeout(retry);retry=null;}if(ws&&ws.readyState===1)ws.close(1000,'Pairing');else connect();return false;}
function modal(){if(!root.document||root.document.getElementById('msfslogger-pairing'))return;var n=root.document.createElement('div');n.id='msfslogger-pairing';n.style.cssText='position:absolute;top:0;left:0;width:100vw;height:100vh;z-index:2147483647;background-color:#111;color:#fff;text-align:center;padding-top:35vh;box-sizing:border-box;font:18px sans-serif';n.innerHTML='<form><label>Pairing code <input inputmode="numeric" maxlength="8"></label> <button type="button">Pair</button></form><div style="margin-top:12px;font-size:14px;color:#ccc">Enter the code shown on the desktop app (MENU, GAUGE PAIR).</div>';n.firstChild.onsubmit=submitPair;var b=n.getElementsByTagName('button')[0];if(b)b.onclick=submitPair;(root.document.body||root.document.documentElement).appendChild(n);}
function patch(o){var r={},a=['serverUrl','trafficEnabled','trafficRadiusM','sim','autoUplink','ingestToken'];o=o&&typeof o==='object'?o:{};a.forEach(function(k){if(own(o,k))r[k]=o[k];});if(!Object.keys(r).length)throw Error('No supported configuration fields');return r;}
var host={hostLabel:'MSFS GAUGE',getConfig:function(){return request('config.get',{},false);},setConfig:function(p){try{return request('config.patch',{patch:patch(p)},true);}catch(e){return Promise.reject(e);}},getConfigPath:function(){return request('config.path.get',{},false);},startUplink:function(){return request('uplink.start',{},true);},stopUplink:function(){return request('uplink.stop',{},true);},restartSidecar:function(){return request('sidecar.restart',{},true);},getStatus:function(){return request('state.get',{},false);},onStatus:function(fn){return sub('status',fn);},onLog:function(fn){return sub('log',fn);},onExit:function(fn){return sub('exit',fn);}};
root.__FMC_HOST__=host;root.msfsloggerGaugeHost={host:host,reconnect:connect,unpair:function(){try{root.localStorage.removeItem(KEY);}catch(e){}if(ws)ws.close(1008,'Unpaired');},suspend:function(){},resume:function(){if(stopped||ws)return;attempt=0;if(retry){root.clearTimeout(retry);retry=null;}connect();},teardown:function(){stopped=true;clearLinkTimers();if(retry)root.clearTimeout(retry);if(stable)root.clearTimeout(stable);if(ws)ws.close(1000,'Page closing');ws=null;}};connect();
}(window));
