import net from 'node:net';
import {createHash,randomBytes} from 'node:crypto';

const GUID='258EAFA5-E914-47DA-95CA-C5AB0DC85B11';
export function encodeClientFrame(opcode,payload=Buffer.alloc(0)){
  payload=Buffer.isBuffer(payload)?payload:Buffer.from(payload);const mask=randomBytes(4),size=payload.length;
  const extra=size<126?0:size<=65535?2:8,frame=Buffer.alloc(2+extra+4+size);frame[0]=0x80|opcode;
  if(size<126)frame[1]=0x80|size;else if(size<=65535){frame[1]=0x80|126;frame.writeUInt16BE(size,2);}else{frame[1]=0x80|127;frame.writeBigUInt64BE(BigInt(size),2);}
  const at=2+extra;mask.copy(frame,at);for(let i=0;i<size;i++)frame[at+4+i]=payload[i]^mask[i%4];return frame;
}
export function decodeServerFrames(buffer){
  const frames=[];let offset=0;
  while(buffer.length-offset>=2){const a=buffer[offset],b=buffer[offset+1],masked=!!(b&0x80);let size=b&0x7f,head=2;if(size===126){if(buffer.length-offset<4)break;size=buffer.readUInt16BE(offset+2);head=4;}else if(size===127){if(buffer.length-offset<10)break;const n=buffer.readBigUInt64BE(offset+2);if(n>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('frame too large');size=Number(n);head=10;}const maskBytes=masked?4:0;if(buffer.length-offset<head+maskBytes+size)break;const payload=Buffer.from(buffer.subarray(offset+head+maskBytes,offset+head+maskBytes+size));if(masked){const key=buffer.subarray(offset+head,offset+head+4);for(let i=0;i<payload.length;i++)payload[i]^=key[i%4];}frames.push({fin:!!(a&0x80),opcode:a&0xf,payload});offset+=head+maskBytes+size;}
  return {frames,rest:buffer.subarray(offset)};
}
export class Rfc6455WebSocket{
  static CONNECTING=0;static OPEN=1;static CLOSING=2;static CLOSED=3;
  constructor(url,{origin,onMilestone}={}){this.url=String(url);this.readyState=0;this.onopen=this.onmessage=this.onclose=this.onerror=null;this.lastMilestone='CREATED';this.failureCode=null;this._onMilestone=typeof onMilestone==='function'?onMilestone:null;this._listeners=new Map(['open','message','error','close'].map(type=>[type,new Set()]));this._closed=false;this._buffer=Buffer.alloc(0);this._writes=[];this._writing=false;const parsed=new URL(this.url);if(parsed.protocol!=='ws:')throw new Error('unsupported websocket scheme');this._key=randomBytes(16).toString('base64');this._expected=createHash('sha1').update(this._key+GUID).digest('base64');this._socket=net.createConnection({host:parsed.hostname,port:Number(parsed.port||80)});this._socket.once('connect',()=>{this._mark('TCP_CONNECT');const host=parsed.port?`${parsed.hostname}:${parsed.port}`:parsed.hostname;this._socket.write(`GET ${parsed.pathname}${parsed.search} HTTP/1.1\r\nHost: ${host}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: ${this._key}\r\nSec-WebSocket-Version: 13\r\nOrigin: ${origin}\r\n\r\n`);});let headers=Buffer.alloc(0);const handshake=data=>{headers=Buffer.concat([headers,data]);const end=headers.indexOf('\r\n\r\n');if(end<0){if(headers.length>8192)this._reject('HTTP_HEADERS_OVERSIZE');return;}this._socket.off('data',handshake);const text=headers.subarray(0,end).toString('latin1'),lines=text.split('\r\n'),status=/^HTTP\/1\.1 101(?: |$)/.test(lines[0]);if(!status)return this._reject('HTTP_UPGRADE_STATUS');this._mark('HTTP_UPGRADE_STATUS');const fields=new Map(lines.slice(1).map(line=>{const at=line.indexOf(':');return [line.slice(0,at).trim().toLowerCase(),line.slice(at+1).trim()];}));if(fields.get('upgrade')?.toLowerCase()!=='websocket'||!fields.get('connection')?.toLowerCase().split(/\s*,\s*/).includes('upgrade'))return this._reject('UPGRADE_HEADER_MISMATCH');if(fields.get('sec-websocket-accept')!==this._expected)return this._reject('ACCEPT_MISMATCH');this.readyState=1;this._socket.on('data',chunk=>this._data(chunk));this._mark('WS_OPEN');this._emit('open',{});const rest=headers.subarray(end+4);if(rest.length)this._data(rest);};this._socket.on('data',handshake);this._socket.on('error',()=>{this.failureCode=this._writing?'SOCKET_WRITE_ERROR':'TCP_CONNECT_ERROR';this._fail(true);});this._socket.on('end',()=>this._finish(1006,''));this._socket.on('close',()=>this._finish(1006,''));}
  _mark(value){this.lastMilestone=value;try{this._onMilestone?.(value);}catch{}}
  _reject(code){this.failureCode=code;this._fail(true);}
  addEventListener(type,listener){if(this._listeners.has(type)&&(typeof listener==='function'||listener&&typeof listener.handleEvent==='function'))this._listeners.get(type).add(listener);}
  removeEventListener(type,listener){this._listeners.get(type)?.delete(listener);}
  _emit(type,detail){const event=Object.freeze({type,target:this,currentTarget:this,...detail});const property=this[`on${type}`];if(typeof property==='function'){try{property.call(this,event);}catch{}}for(const listener of [...(this._listeners.get(type)||[])]){try{if(typeof listener==='function')listener.call(this,event);else listener.handleEvent(event);}catch{}}}
  send(value){if(this.readyState!==1)throw new Error('websocket not open');this._writes.push(encodeClientFrame(1,Buffer.from(String(value))));this._pump();}
  _pump(){if(this._writing||!this._writes.length||this.readyState!==1)return;this._writing=true;const frame=this._writes.shift();this._mark('FRAME_WRITE_STARTED');let callbackDone=false,drained=true;const finish=()=>{if(!callbackDone||!drained)return;this._writing=false;this._mark('FRAME_WRITE_COMPLETED');this._pump();};const accepted=this._socket.write(frame,error=>{if(error){this.failureCode='SOCKET_WRITE_ERROR';return this._fail(true);}callbackDone=true;finish();});if(!accepted){drained=false;this._socket.once('drain',()=>{drained=true;finish();});}}
  close(code=1000,reason=''){if(this.readyState>=2)return;this.readyState=2;const body=Buffer.alloc(2+Buffer.byteLength(reason));body.writeUInt16BE(code);body.write(reason,2);this._socket.end(encodeClientFrame(8,body));}
  _data(chunk){this._buffer=Buffer.concat([this._buffer,chunk]);let decoded;try{decoded=decodeServerFrames(this._buffer);}catch{return this._fail();}this._buffer=decoded.rest;for(const frame of decoded.frames){if(!frame.fin)return this._fail();if(frame.opcode===1)this._emit('message',{data:frame.payload.toString('utf8')});else if(frame.opcode===9)this._socket.write(encodeClientFrame(10,frame.payload));else if(frame.opcode===8){const code=frame.payload.length>=2?frame.payload.readUInt16BE(0):1005,reason=frame.payload.subarray(2).toString('utf8');if(this.readyState===1)this._socket.end(encodeClientFrame(8,frame.payload));this._finish(code,reason);}else if(frame.opcode!==10)this._fail();}}
  _fail(withError=false){if(withError)this._emit('error',{});try{this._socket.destroy();}catch{}this._finish(1006,'');}
  _finish(code,reason){if(this._closed)return;this._closed=true;this.readyState=3;this._emit('close',{code,reason,wasClean:code===1000});}
}
